language: c
compiler: gcc
addons:
    apt:
        packages:
            - python3
            - autoconf
            - automake
            - autopoint
            - libtool
            - gettext
            - libidn11
            - libidn11-dev
            - libidn2-0
            - libidn2-0-dev
            - libicu48
            - libicu-dev
            - libunistring0
            - libunistring-dev

